### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by nate-at-gusto** [palkan/isolator#44]
The HTTP adapter requires `sniffer` which patches `net-http` with `alias_method`. This causes problems when other gems (`rack-mini-profiler`, APMs like `datadog`) use `prepend` to patch the same methods, leading to `stack level too deep`.

One workaround would be if `isolator` did not require `sniffer` unless the `http` isolator was activated.

**Comment by nate-at-gusto** [comment]
nvm, looks like we'll solve this in sniffer.

**Comment by timdiggins** [comment]
Just adding a note here (because this blew up for me, and took a bit of agentic digging to find the solution), that this is not fixed out of the box. 

Options: 
1) either adjust [how you load sniffer in the Gemfile](https://github.com/aderyabin/sniffer#:~:text=If%20you%20want,%27sniffer%27%5D) or,

2) if you're not loading Sniffer in the Gemfile but loading isolator only in some environments to require the all_prepend before require 

```ruby
  require "all_prepend"
  require "isolator"
```

Maybe worth adding to the README
